"""like table update

Revision ID: dc78ed0409bd
Revises: 519f2c656f64
Create Date: 2025-07-17 16:44:05.066884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc78ed0409bd'
down_revision: Union[str, Sequence[str], None] = '519f2c656f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('post_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_likes_dislike'), table_name='likes')
    op.create_foreign_key(None, 'likes', 'post', ['post_id'], ['id'])
    op.drop_column('likes', 'dislike')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('dislike', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_index(op.f('ix_likes_dislike'), 'likes', ['dislike'], unique=False)
    op.drop_column('likes', 'post_id')
    # ### end Alembic commands ###
